blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('create/', views.create_blog_post, name='create_blog_post'),
    path('<int:blog_id>/delete/', views.deletepost, name='deletepost'),
    path('<str:blog_id>/edit/', views.editpost, name='editpost'),
]

portfolio/urls.py
from django.urls import path
from portfolio import views


urlpatterns = [
    path('', views.portfolio_home, name='portfolio_home'),
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include
from password_generator import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('home/', include('portfolio.urls')),
    path('password_generator/', views.password_generator, name='password_generator'),
    path('password/', views.password, name='password'),
    path('about/', views.about, name='about'),
    path('blog/', include('blog.urls')),
    path('todo/', include('todo.urls')),
    path('virus_total/', include('virus_total.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'

urlpatterns = [
    path('', views.welcome, name='welcome'),

    #Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    #ToDos
    path('current/', views.currenttodos, name='currenttodos'),
    path('create/', views.createtodo, name='createtodo'),
    path('completed/', views.completedtodos, name='completedtodos'),
    path('<int:todo_pk>', views.viewtodo, name='viewtodo'),
    path('<int:todo_pk>/complete/', views.completetodo, name='completetodo'),
    path('<int:todo_pk>/delete/', views.deletetodo, name='deletetodo'),

]

virus_total/urls.py
from django.urls import path
from . import views


app_name = 'virus_total'

urlpatterns = [
    path('', views.virus_total_home, name='virus_total_home'),
]

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.

def portfolio_home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nova+Flat&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static  'portfolio/custom.css' %}">
    <title>JM</title>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'portfolio_home' %}">JM Resume</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'portfolio_home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'password_generator' %}">Password Generator</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:welcome' %}">Todo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'virus_total:virus_total_home' %}">Virus Total Checker</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


{% block content %}{% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
<body>

{% block content %}
{% load static %}
<style>
    img {
    display:block;
    margin-left: auto;
    margin-right: auto;
}
    hr.style1 {
    border-top: 2px solid #8c8b8b;
    border-botton: 2px solid #fff;
}
    img.img-fluid {
    max-width:33%;
    max-height: 33%;
    }

    img.me {
    border-radius: 50%
    }

    h2.mt-5 {
    text-align: center;
    }
    div.stinky_linkys {
    display:block;
    text-align:center;
    font-family: 'Nova Flat', cursive;
    }
    a {
    text-decoration: none;
    }
</style>
<div class="row justify-content-center my-3">
    <div class="col-5">
<img src="{% static 'portfolio/small_pro.jpg'  %}" class="me">
    </div>
</div>

<div class="stinky_linkys">
    <a href="{% static 'portfolio/resume.pdf' %}">Resume</a>
    <a href="{% url 'blog:all_blogs' %}">Blog</a>
</div>

<hr class="style1">

<div class="row justify-content-center mb-3">
    <div class="col-md-9 text-center">
        <p class="font-weight-bold">JM is an information technology professional specializing in cyber security. </p>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm">
            <img src="{% static 'portfolio/comptia-cysa-ce-certification.png' %}">
        </div>
        <div class="col-sm">
            <img src="{% static 'portfolio/comptia-it-operations-specialist-cios-stackable-certification.png' %}">
        </div>
        <div class="col-sm">
            <img src="{% static 'portfolio/comptia-linux-network-professional-clnp-stackable-certification.png' %}">
        </div>
        <div class="col-sm">
            <img src="{% static 'portfolio/comptia-linux-powered-by-lpi-certification.png' %}">
        </div>
        <div class="col-sm">
            <img src="{% static 'portfolio/lpic-1-linux-server-professional-certification.png' %}">
        </div>
        <div class="col-sm">
            <img src="{% static 'portfolio/comptia-secure-infrastructure-specialist-csis-stackable-certification.png' %}">
        </div>
        <div class="col-sm">
            <img src="{% static 'portfolio/comptia-security-analytics-professional-csap-stackable-certification.png' %}">
        </div>
        <div class="col-sm">
            <img src="{% static 'portfolio/comptia-security-ce-certification.png' %}">
        </div>
        <div class="col-sm">
            <img src="{% static 'portfolio/comptia-systems-support-specialist-csss-stackable-certification.png' %}">
        </div>
    </div>
</div>

<hr class="style1">
<div class="row">
{% for project in projects %}
<div class="col-lg-4 col-md-6">
    {% if project.url %}
    <a href="{{ project.url }}">
        <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3 class="text-center">{{ project.title }}</h3>

    <p class="text-center">{{ project.description }}</p>
</div>
{% endfor %}
{% endblock %}
</div>
</body>
</html>