blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('create/', views.create_blog_post, name='create_blog_post'),
    path('<int:blog_id>/delete/', views.deletepost, name='deletepost'),
    path('<str:blog_id>/edit/', views.editpost, name='editpost'),
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include
from password_generator import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('home/', include('portfolio.urls')),
    path('password_generator/', views.password_generator, name='password_generator'),
    path('password/', views.password, name='password'),
    path('about/', views.about, name='about'),
    path('blog/', include('blog.urls')),
    path('todo/', include('todo.urls')),
    path('virus_total/', include('virus_total.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Blog(models.Model):
    blog_title = models.CharField(max_length=100)
    blog_author = models.CharField(max_length=20)
    blog_date = models.DateField("Date", default=datetime.date.today)
    blog_post = models.TextField(max_length=10000)

    def __str__(self):
        return self.blog_title

blog/forms.py
from django.forms import ModelForm
from .models import Blog

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['blog_title', 'blog_post']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from .models import Blog
from .forms import BlogForm
from django.views.generic import UpdateView
# Create your views here.

def all_blogs(request):
    blogs = Blog.objects.order_by('-blog_date')
    return render(request, 'blogs/all_blogs.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blogs/detail.html', {'blog':blog})

@user_passes_test(lambda u: u.is_superuser)
def create_blog_post(request):
    if request.method == 'GET':
        return render(request, 'blogs/createblog.html', {'form': BlogForm()})
    else:
        try:
            form = BlogForm(request.POST)
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.save()
            return redirect('blog:all_blogs')
        except ValueError:
            return render(request, 'blogs/createblog.html',
                          {'form': BlogForm(), 'error': 'One or more fields incorrectly filled out.'})

@user_passes_test(lambda u: u.is_superuser)
def deletepost(request, blog_pk):
    todelete = get_object_or_404(Blog, pk=blog_pk, user=request.user)
    if request.method == 'POST':
        todelete.delete()
        return redirect('blog:all_blogs')


@user_passes_test(lambda u: u.is_superuser)
def editpost(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    if request.method == 'GET':
        form = BlogForm(instance=blog)
        return render(request, 'blogs/edit.html', {'blog': blog, 'form': form})
    else:
        try:
            form = BlogForm(request.POST, instance=blog)
            form.save()
            return redirect('blog:all_blogs')
        except ValueError:
            return render(request, 'blogs/all_blogs.html', {'blog': blog, 'form': form, 'error': 'Error'})

blog/templates/blogs/all_blogs.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">JM has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>
{% for blog in blogs %}

<div class="row justify-content-center my-3">
    <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
        <h2>{{ blog.blog_title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.blog_date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.blog_post|striptags|truncatechars:100 }}</h4>
    </div>
</div>
{% endfor %}
{% endblock %}

blog/templates/blogs/createblog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Blog Post</title>
     {% extends 'portfolio/base.html' %}
</head>
<body>
{% block content %}
<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">
            <h1>New Post</h1>

            <h2>{{ error }}</h2>

            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="blog_title">Title:</label>
                    <input type="text" name="blog_title" class="form-control" id="blog_title" required>
                </div>
                <div class="form-group">
                    <label for="blog_post">Blog Post:</label>
                    <textarea name="blog_post" class="form-control" id="blog_post" rows="10"></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-lg">Create!</button>
            </form>
        </div>
</div>

{% endblock %}

</body>
</html>

blog/templates/blogs/detail.html
{% extends 'portfolio/base.html' %}




{% block content %}
<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.blog_title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.blog_date|date:'F jS Y' }}</h5>

<div class="container text-center">
<div class="blog_post text-center" style="max-width: 1000px; margin-left: auto; margin-right: auto; padding: 24px;">



<h5 style="line-height: 1.6;">{{ blog.blog_post|linebreaksbr }}</h5>
    </div>
    </div>
<div class="text-center">
    {% if user.is_superuser %}
    <a href="{% url 'blog:editpost' 10  %}" class="btn btn-primary btn-lg" role="button">Edit</a>
    {% endif %}
</div>
{% endblock %}

blog/templates/blogs/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'portfolio/base.html' %}
    <meta charset="UTF-8">
</head>
<body>
{% block content %}
<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">
            <h1>EDIT POST</h1>

            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="blog_title">Edit</label>
                    <input type="text" name="blog_title" class="form-control" id="blog_title" value="{{ blog.blog_title }}" required>
                </div>
                <div class="form-group">
                    <label for="blog_post">Blog Post:</label>
                    <textarea name="blog_post" class="form-control" id="blog_post" rows="10">{{ blog.blog_post }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-lg" onclick="$('#edit').click()">Edit</button>
            </form>
        </div>
</div>
{% endblock %}


</body>
</html>