blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('create/', views.create_blog_post, name='create_blog_post'),
    path('<int:blog_id>/delete/', views.deletepost, name='deletepost'),
    path('<str:blog_id>/edit/', views.editpost, name='editpost'),
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include
from password_generator import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('home/', include('portfolio.urls')),
    path('password_generator/', views.password_generator, name='password_generator'),
    path('password/', views.password, name='password'),
    path('about/', views.about, name='about'),
    path('blog/', include('blog.urls')),
    path('todo/', include('todo.urls')),
    path('virus_total/', include('virus_total.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'

urlpatterns = [
    path('', views.welcome, name='welcome'),

    #Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    #ToDos
    path('current/', views.currenttodos, name='currenttodos'),
    path('create/', views.createtodo, name='createtodo'),
    path('completed/', views.completedtodos, name='completedtodos'),
    path('<int:todo_pk>', views.viewtodo, name='viewtodo'),
    path('<int:todo_pk>/complete/', views.completetodo, name='completetodo'),
    path('<int:todo_pk>/delete/', views.deletetodo, name='deletetodo'),

]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=50)
    memo = models.TextField(blank=True)
    priority = models.BooleanField(default=False)
    created_time = models.DateTimeField(auto_now_add=True)
    completed_time = models.DateTimeField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm
from .models import Todo

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'memo', 'priority']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import TodoForm
from .models import Todo
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Create your views here.


def welcome(request):
    if request.user.is_authenticated:
        return redirect('todo:currenttodos')
    else:
        return render(request, 'todo/welcome.html')



def signupuser(request):
    if request.user.is_authenticated:
        return redirect('todo:currenttodos')
    else:
        if request.method == 'GET':
            return render(request, 'todo/signupuser.html', {'form':UserCreationForm()})
        else:
            if request.POST['password1'] == request.POST['password2']:
                try:
                    user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                    user.save()
                    login(request, user)
                    return redirect('todo:currenttodos')
                except IntegrityError:
                    return render(request, 'todo/signupuser.html',
                            {'form': UserCreationForm(), 'error': 'Username already taken!'})
            else:
                return render(request, 'todo/signupuser.html', {'form': UserCreationForm(), 'error':'Passwords did not match!'})


@login_required
def currenttodos(request):
    todos = Todo.objects.filter(user=request.user, completed_time__isnull=True)
    return render(request, 'todo/currenttodos.html', {'todos': todos})

@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('todo:loginuser')

def loginuser(request):
    if request.method == 'GET':
        return render(request, 'todo/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'todo/loginuser.html', {'form': AuthenticationForm(), 'error':'Username or Password incorrect.'})
        else:
            login(request,user)
            return redirect('todo:currenttodos')


@login_required
def createtodo(request):
    if request.method == 'GET':
        return render(request, 'todo/createtodo.html', {'form': TodoForm()})
    else:
        try:
            form = TodoForm(request.POST)
            new_do = form.save(commit=False)
            new_do.user = request.user
            new_do.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request, 'todo/createtodo.html', {'form': TodoForm(), 'error': 'One or more fields incorrectly filled out.' })


@login_required
def viewtodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'GET':
        form = TodoForm(instance=todo)
        return render(request, 'todo/viewtodo.html', {'todo':todo, 'form':form})
    else:
        try:
            form = TodoForm(request.POST, instance=todo)
            form.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request, 'todo/viewtodo.html', {'todo':todo, 'form':form, 'error': 'One or more fields incorrectly filled out.'})


@login_required
def completetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.completed_time = timezone.now()
        todo.save()
        return redirect('todo:currenttodos')


@login_required
def deletetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.delete()
        return redirect('todo:currenttodos')


@login_required
def completedtodos(request):
    todos = Todo.objects.filter(user=request.user, completed_time__isnull=False).order_by('-completed_time')
    return render(request, 'todo/completedtodos.html', {'todos': todos})

todo/templates/todo/completedtodos.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'todo/mod_base.html' %}
    <meta charset="UTF-8">
    <title>Completed</title>
</head>
<body>
{% block content %}

You have completed {{ todos.count }} tasks!
<ul>
    {% for todo in todos %}
    <li>
        <a href="{% url 'todo:viewtodo' todo.id %}">
        {% if todo.priority %}
        <strong>{% endif %}{{ todo.title }}{% if todo.priority %}</strong>{% endif %}
        {% if todo.memo %} - {{ todo.memo }} {% endif %}
        {{ todo.completed_time|date:'M j Y H:i' }}
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}
</body>
</html>

todo/templates/todo/createtodo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Todo!</title>
    {% extends 'todo/mod_base.html' %}
</head>
<body>

{% block content %}
<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">
            <h1>Create</h1>

            <h2>{{ error }}</h2>

            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Title:</label>
                    <input type="text" name="title" class="form-control" id="title" required>
                </div>
                <div class="form-group">
                    <label for="memo">Memo:</label>
                    <textarea name="memo" class="form-control" id="memo"></textarea>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="priority" class="form-check-input" id="priority">
                    <label class="form-check-label" for="priority">Priority</label>
                </div>
                <button type="submit" class="btn btn-primary btn-lg">Create!</button>
            </form>
        </div>
</div>
{% endblock %}


</body>
</html>

todo/templates/todo/currenttodos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Current</title>
    {% extends 'todo/mod_base.html' %}

</head>
<body>
{% block content %}
<div class="row justify-content-center mt-5">
        <div class="col-md-5 text-center">
            You have {{ todos.count }} tasks to do!
            <br>
            <br>
            {% if todos %}
                <div class="list-group">
                    {% for todo in todos %}
                        <a href="{% url 'todo:viewtodo' todo.id %}" class="list-group-item list-group-item-action"
                           {% if todo.priority %} list-group-item-action- active {% endif %}>
                           <strong>{{ todo.title }}</strong>
                            {% if todo.memo %} - {{ todo.memo|truncatechars:30 }} {% endif %}</a>
                    {% endfor %}
                </div>
            {% endif %}
            <br>
            <a role="button" class="btn btn-primary btn-lg" href="{% url 'todo:createtodo' %}">Create Todo!</a>
        </div>
</div>
{% endblock %}
</body>
</html>

todo/templates/todo/loginuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LogIN</title>

    {% extends 'todo/mod_base.html' %}

</head>
<body>

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-5">
        <h1>LOGIN</h1>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}

    <form method="POST">
    {% csrf_token %}
        <div class="row justify-content-center">
            <div class="form-group">
                <label for="username" class="col-sm-4 col-form-label">Username</label>
                <div class="col-sm-10">
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" name="password" class="form-control" id="password">
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-sm-0 text-center">
                        <button type="submit" class="btn btn-primary">Login</button>
                        </form>
        <hr>
                    </div>
                </div>
            </div>
</div>
</div>

{% endblock %}
</body>
</html>

todo/templates/todo/mod_base.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nova+Flat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static  'portfolio/custom.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>JM</title>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'portfolio_home' %}">JM Resume</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'portfolio_home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'password_generator' %}">Password Generator</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% if user.is_authenticated %}
<div class="d-flex justify-content-end">
  <div class="col-sm-0 text-center">
    <form action="{% url 'todo:logoutuser' %}" method="POST">
                {% csrf_token %}
            <button class="btn btn-primary btn-lg" type="submit">Logout</button>
    </form>
  </div>
</div>
<br>
{% endif %}
  {% block content %}{% endblock %}

todo/templates/todo/signupuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
    {% extends 'todo/mod_base.html' %}
</head>
<body>
{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
    <form method="POST">
    {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
            <small id="usernameHelp" class="form-text text-muted">Your username must be unique.</small>
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" name="password1" class="form-control" id="password1">
        </div>
        <div class="form-group">
            <label for="password2">Confirm Password</label>
            <input type="password" name="password2" class="form-control" id="password2">
        </div>
    <div class="containter">
        <div class="row">
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </div>
        </div>
    </div>
    </form>
        <hr>
        <div class="text-center">
            Already signed up? <a href="{% url 'todo:loginuser' %}">Login</a>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

todo/templates/todo/viewtodo.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'todo/mod_base.html' %}
    <meta charset="UTF-8">
    <title>DetailView</title>
</head>
<body>
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>{{ todo.title }}</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" class="form-control" id="title" value="{{ todo.title }}" required>
                </div>
                <div class="form-group">
                    <label for="memo">Memo</label>
                    <textarea name="memo" rows="5" class="form-control" id="memo" >{{ todo.memo }}</textarea>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="priority" class="form-check-input" id="priority" {% if todo.priority %}checked{% endif %}>
                    <label class="form-check-label" for="priority">Priority</label>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="button" class="btn btn-success" onclick="$('#complete').click()">Complete</button>
                <button type="button" class="btn btn-danger" onclick="$('#delete').click()">Delete</button>
            </form>
        </div>
    </div>
    {% if todo.completed_time is None %}
        <form style='display: none;' method="POST" action="{% url 'todo:completetodo' todo.id %}">
            {% csrf_token %}
            <button id="complete" type="submit">Complete</button>
        </form>
    {% endif %}
    <form style='display: none;' method="POST" action="{% url 'todo:deletetodo' todo.id %}">
        {% csrf_token %}
        <button id="delete" type="submit">Delete</button>
    </form>
{% endblock %}

todo/templates/todo/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDo Home</title>

    {% extends 'todo/mod_base.html' %}
</head>
<body>

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

    <div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">

            <h1>Welcome to the ToDo app!</h1>
            <a role="button" class="btn btn-primary btn-lg" href="{% url 'todo:signupuser' %}">Get Started!</a>
</div>
    </div>
{% endblock %}

</body>
</html>